- config.php.example
- logic.php
> Add map link

- README.md
- config.php.example
- logic.php
- Reordered buttons so users need to select a time first (maybe make this user-configurable in the future?)
- Added required plugins for apache2 into README.MD
> Reordered buttons and updated README to include required plugins for apache2

- tr/language.json
> Italian translation of file language.json

- tr/language.json
I swear, my editor (Atom) didn't even let me know that there was a different identation.
Should be corrected by now.
> Fixed identation

- tr/language.json
My brother corrected me as he is more expert on the game.
Sorry for the previous translation.
> Renamed word for 'Quest' to 'Spedizione', more correct

- logic.php
Get the address from google and store it in the SQL.
> Update address in SQL if NULL

- getGOHubDB.php
Fixes an issue where pokemons without having a normal form got added twice with their first form, e.g. Giratina.
> Gohub script: Fix pokemons not having a normal form

- index.php
> Fix user update check

- README.md
- config.php.example
- logic.php
Finally 😁 
Adds a RAID_FIRST_START option to add an additional voting slot right after the raid start (based on the config).
> Add RAID_FIRST_START option

- logic.php
Initial version included some bugs (duplicate voting slots like 12:15, 12:15, 12:30) etc.
Reworked the if-clause to match any cases and avoid those issues :)
> Fix RAID_FIRST_START

- lang/pokemon_forms.json
> Added NL translation

- logic.php
- mods/edit_raidlevel.php
- Shows raid bosses directly if there is just 1 raid boss which is often at level 5
- Hide ex-raids from non-BOT_ADMINS
> Shows raid bosses directly and hide ex-raids

- mods/raid_set_poke.php
Updates every raid poll after /pokemon
> Automatically update raid poll after /pokemon

- logic.php
Should fix the bug with the missing raid levels.
> Oops.. Overwriting $rs is a bad idea

- logic.php
Fix that stupid copy+paste bug
> Oops... I did it again :D

- logic.php
- mods/edit_raidlevel.php
With this patch we check now 3 times for duplicate raids:
- Check for active raids based on first letter and show a warning ⚠️ sign before the gym name
- Check for duplicate raids based on gym id, so once the gym get's selected
- Check for duplicate raids when selecting the start time of the raid
This should help to avoid/prevent duplicate raids when manually creating them which could happen if multiple people are creating the raid at almost the same time.
> Early check for duplicate raids

- commands/help.php
- lang/help.json
Added info how to import portals as gyms from telegram ingress bots.
> Add gyms via Ingress Bots was missing in help

- mods/vote_pokemon.php
Avoid stupid mysql error 1093 by wrapping the subquery in another subquery 🤦‍♂
> Fix MySQL error 1093

- README.md
The #debug section also needs improvement to make install easier if there's issues.
> Improve webhook install documentation

- README.md
- docker-compose.yml
- docker-custom/Dockerfile
- docker-custom/cronjob
Added Dockertemplate and readme for launching the Raidbot in Docker
> Dockertemplate

- logic.php
> Fix inline raid poll sharing

- logic.php
> Fixed show_gym with /start ***

- getGOHubDB.php
Because the eggs didn't have a shiny value they won't import. Default set to 0.
> Egg are missing the shiny value.

- logic.php
It's not a bug... it's a feature 🤣
> Oops... forgot to enable anti testing mode :D

- commands/raid_from_webhook.php
- Reduced raid info updates sent to TG
- Fixed gym info not updating to db
- Added curl_json_multi_request
I was unable to test RAID_LOCATION, please check that it works
> Performance improvements to raid_from_webhook

- config/config.json.example
removed last comma in config.json.example to have a valid JSON file
> removed last comma in config.json.example

- logic.php
Works now as it should. Tested with several raids and users :)
> Small fixes for the new remote feature

- mods/importal.php
The escape function needs to be called earlier. Importing gyms with special characters will give an error instead. The file name now also has no apostrophes in its name.
> Fixed importal.php

- mods/vote_pokemon.php
Same as my commit before, but this time without changes to core link 😬
> Fix for vote_pokemon.php deleting attendance

- logic.php
- raidpicture.php
Added regular expression to filter user input to reduce the possibility of SQL injection.
> Filter user input

- logic/mapslink.php
Google has changed the url https://maps.google.com to https://www.google.de/maps
> Fix Google Maps URL

- mods/trainer_level.php
Change the level cap from 40 to 50.
> Ready for level 50

- sql/pokemon-raid-bot.sql
- sql/upgrade/2.0.341.2.sql
- Removed some stuff from sql upgrades that was left there by accident
- Added unique key to pokemon-table in sql/pokemon-raid-bot.sql
> Unique key fix

- logic/send_response_vote.php
Thanks to @AlexxBoo for reporting and debugging this one!
Issue was that in 32bit systems array keys get truncated and thus some data was lost
> A fix to issue #217

- logic/show_raid_poll.php
PHP Notice:  Undefined variable: raid_pokemon_form_name in /var/www/html/logic/show_raid_poll.php on line 100
> fix php notice

- commands/deletegym.php
- commands/gym.php
- commands/listall.php
- commands/start.php
- config/defaults-config.json
- docs/index.rst
- lang/language.json
- logic/raid_edit_gym_keys.php
- logic/raid_edit_gyms_first_letter_keys.php
- mods/gym_delete.php
- mods/gym_details.php
- mods/gym_hidden_letter.php
- mods/gym_letter.php
- mods/list_by_gym.php
- mods/list_by_gym_letter.php
- mods/listall.php
- mods/raid_by_gym.php
- mods/raid_by_gym_letter.php
You can create areas in geoconfig.json to divide gyms into when creating listings in `/start`, `/list`, etc.
> New gym area feature 

- mods/pokebattler.php
We now first check breaking news section for active bosses (t5 and mega) and after that run through tiers to fill in the rest
> Reworked Pokebattler import

- core/bot/db.php
- core/bot/logic/sql_utils.php
- docs/docker.rst
- docs/manual_install.rst
As long as the DB exists and we have permissions to create tables it
should work.
> Add automatic initialization of DB schema.

- config/config.json.example
- docs/_static/custom.css
- docs/conf.py
- docs/debug.rst
- docs/index.rst
- docs/manual_install.rst
- Fix `config.json.example` to not suggest an obsolete log path
- Add a new docs page for debugging that instructs how to change log levels and where the logs are usually located
- Minor tweaks to manual_install instructions.
> Issues from ftp funland

- commands/deletegym.php
- commands/gym.php
- commands/listall.php
- commands/start.php
- config/defaults-config.json
- docs/index.rst
- lang/language.json
- logic/raid_edit_gym_keys.php
- logic/raid_edit_gyms_first_letter_keys.php
- mods/gym_delete.php
- mods/gym_details.php
- mods/gym_hidden_letter.php
- mods/gym_letter.php
- mods/list_by_gym.php
- mods/list_by_gym_letter.php
- mods/listall.php
- mods/raid_by_gym.php
- mods/raid_by_gym_letter.php
You can create areas in geoconfig_gym_areas.json to divide gyms into when creating listings in /start, /list, etc.
> New gym area feature 2nd try
